# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Account(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'used_quota_private': 'int',
        'modified_date': 'str',
        'used_quota': 'int',
        'created_date': 'str',
        'quota': 'int',
        'group_id': 'int',
        'institution_user_id': 'str',
        'institution_id': 'int',
        'email': 'str',
        'used_quota_public': 'int',
        'pending_quota_request': 'bool',
        'active': 'int',
        'maximum_file_size': 'int'
    }

    attribute_map = {
        'id': 'id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'used_quota_private': 'used_quota_private',
        'modified_date': 'modified_date',
        'used_quota': 'used_quota',
        'created_date': 'created_date',
        'quota': 'quota',
        'group_id': 'group_id',
        'institution_user_id': 'institution_user_id',
        'institution_id': 'institution_id',
        'email': 'email',
        'used_quota_public': 'used_quota_public',
        'pending_quota_request': 'pending_quota_request',
        'active': 'active',
        'maximum_file_size': 'maximum_file_size'
    }

    def __init__(self, id=None, first_name=None, last_name=None, used_quota_private=None, modified_date=None, used_quota=None, created_date=None, quota=None, group_id=None, institution_user_id=None, institution_id=None, email=None, used_quota_public=None, pending_quota_request=None, active=None, maximum_file_size=None):  # noqa: E501
        """Account - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._first_name = None
        self._last_name = None
        self._used_quota_private = None
        self._modified_date = None
        self._used_quota = None
        self._created_date = None
        self._quota = None
        self._group_id = None
        self._institution_user_id = None
        self._institution_id = None
        self._email = None
        self._used_quota_public = None
        self._pending_quota_request = None
        self._active = None
        self._maximum_file_size = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if used_quota_private is not None:
            self.used_quota_private = used_quota_private
        if modified_date is not None:
            self.modified_date = modified_date
        if used_quota is not None:
            self.used_quota = used_quota
        if created_date is not None:
            self.created_date = created_date
        if quota is not None:
            self.quota = quota
        if group_id is not None:
            self.group_id = group_id
        if institution_user_id is not None:
            self.institution_user_id = institution_user_id
        if institution_id is not None:
            self.institution_id = institution_id
        if email is not None:
            self.email = email
        if used_quota_public is not None:
            self.used_quota_public = used_quota_public
        if pending_quota_request is not None:
            self.pending_quota_request = pending_quota_request
        if active is not None:
            self.active = active
        if maximum_file_size is not None:
            self.maximum_file_size = maximum_file_size

    @property
    def id(self):
        """Gets the id of this Account.  # noqa: E501

        Account id  # noqa: E501

        :return: The id of this Account.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Account.

        Account id  # noqa: E501

        :param id: The id of this Account.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def first_name(self):
        """Gets the first_name of this Account.  # noqa: E501

        First Name  # noqa: E501

        :return: The first_name of this Account.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Account.

        First Name  # noqa: E501

        :param first_name: The first_name of this Account.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Account.  # noqa: E501

        Last Name  # noqa: E501

        :return: The last_name of this Account.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Account.

        Last Name  # noqa: E501

        :param last_name: The last_name of this Account.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def used_quota_private(self):
        """Gets the used_quota_private of this Account.  # noqa: E501

        Account used private quota  # noqa: E501

        :return: The used_quota_private of this Account.  # noqa: E501
        :rtype: int
        """
        return self._used_quota_private

    @used_quota_private.setter
    def used_quota_private(self, used_quota_private):
        """Sets the used_quota_private of this Account.

        Account used private quota  # noqa: E501

        :param used_quota_private: The used_quota_private of this Account.  # noqa: E501
        :type: int
        """

        self._used_quota_private = used_quota_private

    @property
    def modified_date(self):
        """Gets the modified_date of this Account.  # noqa: E501

        Date of last account modification  # noqa: E501

        :return: The modified_date of this Account.  # noqa: E501
        :rtype: str
        """
        return self._modified_date

    @modified_date.setter
    def modified_date(self, modified_date):
        """Sets the modified_date of this Account.

        Date of last account modification  # noqa: E501

        :param modified_date: The modified_date of this Account.  # noqa: E501
        :type: str
        """

        self._modified_date = modified_date

    @property
    def used_quota(self):
        """Gets the used_quota of this Account.  # noqa: E501

        Account total used quota  # noqa: E501

        :return: The used_quota of this Account.  # noqa: E501
        :rtype: int
        """
        return self._used_quota

    @used_quota.setter
    def used_quota(self, used_quota):
        """Sets the used_quota of this Account.

        Account total used quota  # noqa: E501

        :param used_quota: The used_quota of this Account.  # noqa: E501
        :type: int
        """

        self._used_quota = used_quota

    @property
    def created_date(self):
        """Gets the created_date of this Account.  # noqa: E501

        Date when account was created  # noqa: E501

        :return: The created_date of this Account.  # noqa: E501
        :rtype: str
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this Account.

        Date when account was created  # noqa: E501

        :param created_date: The created_date of this Account.  # noqa: E501
        :type: str
        """

        self._created_date = created_date

    @property
    def quota(self):
        """Gets the quota of this Account.  # noqa: E501

        Account quota  # noqa: E501

        :return: The quota of this Account.  # noqa: E501
        :rtype: int
        """
        return self._quota

    @quota.setter
    def quota(self, quota):
        """Sets the quota of this Account.

        Account quota  # noqa: E501

        :param quota: The quota of this Account.  # noqa: E501
        :type: int
        """

        self._quota = quota

    @property
    def group_id(self):
        """Gets the group_id of this Account.  # noqa: E501

        Account group id  # noqa: E501

        :return: The group_id of this Account.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this Account.

        Account group id  # noqa: E501

        :param group_id: The group_id of this Account.  # noqa: E501
        :type: int
        """

        self._group_id = group_id

    @property
    def institution_user_id(self):
        """Gets the institution_user_id of this Account.  # noqa: E501

        Account institution user id  # noqa: E501

        :return: The institution_user_id of this Account.  # noqa: E501
        :rtype: str
        """
        return self._institution_user_id

    @institution_user_id.setter
    def institution_user_id(self, institution_user_id):
        """Sets the institution_user_id of this Account.

        Account institution user id  # noqa: E501

        :param institution_user_id: The institution_user_id of this Account.  # noqa: E501
        :type: str
        """

        self._institution_user_id = institution_user_id

    @property
    def institution_id(self):
        """Gets the institution_id of this Account.  # noqa: E501

        Account institution  # noqa: E501

        :return: The institution_id of this Account.  # noqa: E501
        :rtype: int
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """Sets the institution_id of this Account.

        Account institution  # noqa: E501

        :param institution_id: The institution_id of this Account.  # noqa: E501
        :type: int
        """

        self._institution_id = institution_id

    @property
    def email(self):
        """Gets the email of this Account.  # noqa: E501

        User email  # noqa: E501

        :return: The email of this Account.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Account.

        User email  # noqa: E501

        :param email: The email of this Account.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def used_quota_public(self):
        """Gets the used_quota_public of this Account.  # noqa: E501

        Account public used quota  # noqa: E501

        :return: The used_quota_public of this Account.  # noqa: E501
        :rtype: int
        """
        return self._used_quota_public

    @used_quota_public.setter
    def used_quota_public(self, used_quota_public):
        """Sets the used_quota_public of this Account.

        Account public used quota  # noqa: E501

        :param used_quota_public: The used_quota_public of this Account.  # noqa: E501
        :type: int
        """

        self._used_quota_public = used_quota_public

    @property
    def pending_quota_request(self):
        """Gets the pending_quota_request of this Account.  # noqa: E501

        True if a quota request is pending  # noqa: E501

        :return: The pending_quota_request of this Account.  # noqa: E501
        :rtype: bool
        """
        return self._pending_quota_request

    @pending_quota_request.setter
    def pending_quota_request(self, pending_quota_request):
        """Sets the pending_quota_request of this Account.

        True if a quota request is pending  # noqa: E501

        :param pending_quota_request: The pending_quota_request of this Account.  # noqa: E501
        :type: bool
        """

        self._pending_quota_request = pending_quota_request

    @property
    def active(self):
        """Gets the active of this Account.  # noqa: E501

        Account activity status  # noqa: E501

        :return: The active of this Account.  # noqa: E501
        :rtype: int
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Account.

        Account activity status  # noqa: E501

        :param active: The active of this Account.  # noqa: E501
        :type: int
        """

        self._active = active

    @property
    def maximum_file_size(self):
        """Gets the maximum_file_size of this Account.  # noqa: E501

        Maximum upload size for account  # noqa: E501

        :return: The maximum_file_size of this Account.  # noqa: E501
        :rtype: int
        """
        return self._maximum_file_size

    @maximum_file_size.setter
    def maximum_file_size(self, maximum_file_size):
        """Sets the maximum_file_size of this Account.

        Maximum upload size for account  # noqa: E501

        :param maximum_file_size: The maximum_file_size of this Account.  # noqa: E501
        :type: int
        """

        self._maximum_file_size = maximum_file_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Account, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Account):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
