# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ArticlesCreator(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'articles': 'list[int]'
    }

    attribute_map = {
        'articles': 'articles'
    }

    def __init__(self, articles=None):  # noqa: E501
        """ArticlesCreator - a model defined in Swagger"""  # noqa: E501

        self._articles = None
        self.discriminator = None

        self.articles = articles

    @property
    def articles(self):
        """Gets the articles of this ArticlesCreator.  # noqa: E501

        List of article ids  # noqa: E501

        :return: The articles of this ArticlesCreator.  # noqa: E501
        :rtype: list[int]
        """
        return self._articles

    @articles.setter
    def articles(self, articles):
        """Sets the articles of this ArticlesCreator.

        List of article ids  # noqa: E501

        :param articles: The articles of this ArticlesCreator.  # noqa: E501
        :type: list[int]
        """
        if articles is None:
            raise ValueError("Invalid value for `articles`, must not be `None`")  # noqa: E501

        self._articles = articles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArticlesCreator, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArticlesCreator):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
