# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Collection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'title': 'str',
        'doi': 'str',
        'handle': 'str',
        'url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'doi': 'doi',
        'handle': 'handle',
        'url': 'url'
    }

    def __init__(self, id=None, title=None, doi=None, handle=None, url=None):  # noqa: E501
        """Collection - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._title = None
        self._doi = None
        self._handle = None
        self._url = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if doi is not None:
            self.doi = doi
        if handle is not None:
            self.handle = handle
        if url is not None:
            self.url = url

    @property
    def id(self):
        """Gets the id of this Collection.  # noqa: E501

        Collection id  # noqa: E501

        :return: The id of this Collection.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Collection.

        Collection id  # noqa: E501

        :param id: The id of this Collection.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this Collection.  # noqa: E501

        Collection title  # noqa: E501

        :return: The title of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Collection.

        Collection title  # noqa: E501

        :param title: The title of this Collection.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def doi(self):
        """Gets the doi of this Collection.  # noqa: E501

        Collection DOI  # noqa: E501

        :return: The doi of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._doi

    @doi.setter
    def doi(self, doi):
        """Sets the doi of this Collection.

        Collection DOI  # noqa: E501

        :param doi: The doi of this Collection.  # noqa: E501
        :type: str
        """

        self._doi = doi

    @property
    def handle(self):
        """Gets the handle of this Collection.  # noqa: E501

        Collection Handle  # noqa: E501

        :return: The handle of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._handle

    @handle.setter
    def handle(self, handle):
        """Sets the handle of this Collection.

        Collection Handle  # noqa: E501

        :param handle: The handle of this Collection.  # noqa: E501
        :type: str
        """

        self._handle = handle

    @property
    def url(self):
        """Gets the url of this Collection.  # noqa: E501

        Api endpoint  # noqa: E501

        :return: The url of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Collection.

        Api endpoint  # noqa: E501

        :param url: The url of this Collection.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Collection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Collection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
