# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CollectionSearch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_doi': 'str',
        'doi': 'str',
        'handle': 'str',
        'order': 'str'
    }

    attribute_map = {
        'resource_doi': 'resource_doi',
        'doi': 'doi',
        'handle': 'handle',
        'order': 'order'
    }

    def __init__(self, resource_doi=None, doi=None, handle=None, order='created_date'):  # noqa: E501
        """CollectionSearch - a model defined in Swagger"""  # noqa: E501

        self._resource_doi = None
        self._doi = None
        self._handle = None
        self._order = None
        self.discriminator = None

        if resource_doi is not None:
            self.resource_doi = resource_doi
        if doi is not None:
            self.doi = doi
        if handle is not None:
            self.handle = handle
        if order is not None:
            self.order = order

    @property
    def resource_doi(self):
        """Gets the resource_doi of this CollectionSearch.  # noqa: E501

        Only return collections with this resource_doi  # noqa: E501

        :return: The resource_doi of this CollectionSearch.  # noqa: E501
        :rtype: str
        """
        return self._resource_doi

    @resource_doi.setter
    def resource_doi(self, resource_doi):
        """Sets the resource_doi of this CollectionSearch.

        Only return collections with this resource_doi  # noqa: E501

        :param resource_doi: The resource_doi of this CollectionSearch.  # noqa: E501
        :type: str
        """

        self._resource_doi = resource_doi

    @property
    def doi(self):
        """Gets the doi of this CollectionSearch.  # noqa: E501

        Only return collections with this doi  # noqa: E501

        :return: The doi of this CollectionSearch.  # noqa: E501
        :rtype: str
        """
        return self._doi

    @doi.setter
    def doi(self, doi):
        """Sets the doi of this CollectionSearch.

        Only return collections with this doi  # noqa: E501

        :param doi: The doi of this CollectionSearch.  # noqa: E501
        :type: str
        """

        self._doi = doi

    @property
    def handle(self):
        """Gets the handle of this CollectionSearch.  # noqa: E501

        Only return collections with this handle  # noqa: E501

        :return: The handle of this CollectionSearch.  # noqa: E501
        :rtype: str
        """
        return self._handle

    @handle.setter
    def handle(self, handle):
        """Sets the handle of this CollectionSearch.

        Only return collections with this handle  # noqa: E501

        :param handle: The handle of this CollectionSearch.  # noqa: E501
        :type: str
        """

        self._handle = handle

    @property
    def order(self):
        """Gets the order of this CollectionSearch.  # noqa: E501

        The field by which to order.  # noqa: E501

        :return: The order of this CollectionSearch.  # noqa: E501
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this CollectionSearch.

        The field by which to order.  # noqa: E501

        :param order: The order of this CollectionSearch.  # noqa: E501
        :type: str
        """
        allowed_values = ["published_date", "modified_date", "views", "shares", "cites"]  # noqa: E501
        if order not in allowed_values:
            raise ValueError(
                "Invalid value for `order` ({0}), must be one of {1}"  # noqa: E501
                .format(order, allowed_values)
            )

        self._order = order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CollectionSearch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionSearch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
