# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FundingInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'title': 'str',
        'grant_code': 'str',
        'funder_name': 'str',
        'is_user_defined': 'bool',
        'url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'grant_code': 'grant_code',
        'funder_name': 'funder_name',
        'is_user_defined': 'is_user_defined',
        'url': 'url'
    }

    def __init__(self, id=None, title=None, grant_code=None, funder_name=None, is_user_defined=None, url=None):  # noqa: E501
        """FundingInformation - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._title = None
        self._grant_code = None
        self._funder_name = None
        self._is_user_defined = None
        self._url = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if grant_code is not None:
            self.grant_code = grant_code
        if funder_name is not None:
            self.funder_name = funder_name
        if is_user_defined is not None:
            self.is_user_defined = is_user_defined
        if url is not None:
            self.url = url

    @property
    def id(self):
        """Gets the id of this FundingInformation.  # noqa: E501

        Funding id  # noqa: E501

        :return: The id of this FundingInformation.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FundingInformation.

        Funding id  # noqa: E501

        :param id: The id of this FundingInformation.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this FundingInformation.  # noqa: E501

        The funding name  # noqa: E501

        :return: The title of this FundingInformation.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this FundingInformation.

        The funding name  # noqa: E501

        :param title: The title of this FundingInformation.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def grant_code(self):
        """Gets the grant_code of this FundingInformation.  # noqa: E501

        The grant code  # noqa: E501

        :return: The grant_code of this FundingInformation.  # noqa: E501
        :rtype: str
        """
        return self._grant_code

    @grant_code.setter
    def grant_code(self, grant_code):
        """Sets the grant_code of this FundingInformation.

        The grant code  # noqa: E501

        :param grant_code: The grant_code of this FundingInformation.  # noqa: E501
        :type: str
        """

        self._grant_code = grant_code

    @property
    def funder_name(self):
        """Gets the funder_name of this FundingInformation.  # noqa: E501

        Funder's name  # noqa: E501

        :return: The funder_name of this FundingInformation.  # noqa: E501
        :rtype: str
        """
        return self._funder_name

    @funder_name.setter
    def funder_name(self, funder_name):
        """Sets the funder_name of this FundingInformation.

        Funder's name  # noqa: E501

        :param funder_name: The funder_name of this FundingInformation.  # noqa: E501
        :type: str
        """

        self._funder_name = funder_name

    @property
    def is_user_defined(self):
        """Gets the is_user_defined of this FundingInformation.  # noqa: E501

        Return whether the grant has been introduced manually  # noqa: E501

        :return: The is_user_defined of this FundingInformation.  # noqa: E501
        :rtype: bool
        """
        return self._is_user_defined

    @is_user_defined.setter
    def is_user_defined(self, is_user_defined):
        """Sets the is_user_defined of this FundingInformation.

        Return whether the grant has been introduced manually  # noqa: E501

        :param is_user_defined: The is_user_defined of this FundingInformation.  # noqa: E501
        :type: bool
        """

        self._is_user_defined = is_user_defined

    @property
    def url(self):
        """Gets the url of this FundingInformation.  # noqa: E501

        The grant url  # noqa: E501

        :return: The url of this FundingInformation.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this FundingInformation.

        The grant url  # noqa: E501

        :param url: The url of this FundingInformation.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FundingInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FundingInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
