# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Group(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'resource_id': 'str',
        'parent_id': 'int',
        'association_criteria': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'resource_id': 'resource_id',
        'parent_id': 'parent_id',
        'association_criteria': 'association_criteria'
    }

    def __init__(self, id=None, name=None, resource_id=None, parent_id=None, association_criteria=None):  # noqa: E501
        """Group - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._resource_id = None
        self._parent_id = None
        self._association_criteria = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if resource_id is not None:
            self.resource_id = resource_id
        if parent_id is not None:
            self.parent_id = parent_id
        if association_criteria is not None:
            self.association_criteria = association_criteria

    @property
    def id(self):
        """Gets the id of this Group.  # noqa: E501

        Group id  # noqa: E501

        :return: The id of this Group.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Group.

        Group id  # noqa: E501

        :param id: The id of this Group.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Group.  # noqa: E501

        Group name  # noqa: E501

        :return: The name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.

        Group name  # noqa: E501

        :param name: The name of this Group.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def resource_id(self):
        """Gets the resource_id of this Group.  # noqa: E501

        Group resource id  # noqa: E501

        :return: The resource_id of this Group.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this Group.

        Group resource id  # noqa: E501

        :param resource_id: The resource_id of this Group.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    @property
    def parent_id(self):
        """Gets the parent_id of this Group.  # noqa: E501

        Parent group if any  # noqa: E501

        :return: The parent_id of this Group.  # noqa: E501
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this Group.

        Parent group if any  # noqa: E501

        :param parent_id: The parent_id of this Group.  # noqa: E501
        :type: int
        """

        self._parent_id = parent_id

    @property
    def association_criteria(self):
        """Gets the association_criteria of this Group.  # noqa: E501

        HR code associated with group, if code exists  # noqa: E501

        :return: The association_criteria of this Group.  # noqa: E501
        :rtype: str
        """
        return self._association_criteria

    @association_criteria.setter
    def association_criteria(self, association_criteria):
        """Sets the association_criteria of this Group.

        HR code associated with group, if code exists  # noqa: E501

        :param association_criteria: The association_criteria of this Group.  # noqa: E501
        :type: str
        """

        self._association_criteria = association_criteria

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Group, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
