# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PrivateFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'viewer_type': 'str',
        'preview_state': 'str',
        'upload_url': 'str',
        'upload_token': 'str'
    }

    attribute_map = {
        'viewer_type': 'viewer_type',
        'preview_state': 'preview_state',
        'upload_url': 'upload_url',
        'upload_token': 'upload_token'
    }

    def __init__(self, viewer_type=None, preview_state=None, upload_url=None, upload_token=None):  # noqa: E501
        """PrivateFile - a model defined in Swagger"""  # noqa: E501

        self._viewer_type = None
        self._preview_state = None
        self._upload_url = None
        self._upload_token = None
        self.discriminator = None

        if viewer_type is not None:
            self.viewer_type = viewer_type
        if preview_state is not None:
            self.preview_state = preview_state
        if upload_url is not None:
            self.upload_url = upload_url
        if upload_token is not None:
            self.upload_token = upload_token

    @property
    def viewer_type(self):
        """Gets the viewer_type of this PrivateFile.  # noqa: E501

        File viewer type  # noqa: E501

        :return: The viewer_type of this PrivateFile.  # noqa: E501
        :rtype: str
        """
        return self._viewer_type

    @viewer_type.setter
    def viewer_type(self, viewer_type):
        """Sets the viewer_type of this PrivateFile.

        File viewer type  # noqa: E501

        :param viewer_type: The viewer_type of this PrivateFile.  # noqa: E501
        :type: str
        """

        self._viewer_type = viewer_type

    @property
    def preview_state(self):
        """Gets the preview_state of this PrivateFile.  # noqa: E501

        File preview state  # noqa: E501

        :return: The preview_state of this PrivateFile.  # noqa: E501
        :rtype: str
        """
        return self._preview_state

    @preview_state.setter
    def preview_state(self, preview_state):
        """Sets the preview_state of this PrivateFile.

        File preview state  # noqa: E501

        :param preview_state: The preview_state of this PrivateFile.  # noqa: E501
        :type: str
        """

        self._preview_state = preview_state

    @property
    def upload_url(self):
        """Gets the upload_url of this PrivateFile.  # noqa: E501

        Upload url for file  # noqa: E501

        :return: The upload_url of this PrivateFile.  # noqa: E501
        :rtype: str
        """
        return self._upload_url

    @upload_url.setter
    def upload_url(self, upload_url):
        """Sets the upload_url of this PrivateFile.

        Upload url for file  # noqa: E501

        :param upload_url: The upload_url of this PrivateFile.  # noqa: E501
        :type: str
        """

        self._upload_url = upload_url

    @property
    def upload_token(self):
        """Gets the upload_token of this PrivateFile.  # noqa: E501

        Token for file upload  # noqa: E501

        :return: The upload_token of this PrivateFile.  # noqa: E501
        :rtype: str
        """
        return self._upload_token

    @upload_token.setter
    def upload_token(self, upload_token):
        """Sets the upload_token of this PrivateFile.

        Token for file upload  # noqa: E501

        :param upload_token: The upload_token of this PrivateFile.  # noqa: E501
        :type: str
        """

        self._upload_token = upload_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrivateFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrivateFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
