# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ShortAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'institution_id': 'int',
        'email': 'str',
        'active': 'int',
        'institution_user_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'institution_id': 'institution_id',
        'email': 'email',
        'active': 'active',
        'institution_user_id': 'institution_user_id'
    }

    def __init__(self, id=None, first_name=None, last_name=None, institution_id=None, email=None, active=None, institution_user_id=None):  # noqa: E501
        """ShortAccount - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._first_name = None
        self._last_name = None
        self._institution_id = None
        self._email = None
        self._active = None
        self._institution_user_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if institution_id is not None:
            self.institution_id = institution_id
        if email is not None:
            self.email = email
        if active is not None:
            self.active = active
        if institution_user_id is not None:
            self.institution_user_id = institution_user_id

    @property
    def id(self):
        """Gets the id of this ShortAccount.  # noqa: E501

        Account id  # noqa: E501

        :return: The id of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ShortAccount.

        Account id  # noqa: E501

        :param id: The id of this ShortAccount.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def first_name(self):
        """Gets the first_name of this ShortAccount.  # noqa: E501

        First Name  # noqa: E501

        :return: The first_name of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this ShortAccount.

        First Name  # noqa: E501

        :param first_name: The first_name of this ShortAccount.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this ShortAccount.  # noqa: E501

        Last Name  # noqa: E501

        :return: The last_name of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this ShortAccount.

        Last Name  # noqa: E501

        :param last_name: The last_name of this ShortAccount.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def institution_id(self):
        """Gets the institution_id of this ShortAccount.  # noqa: E501

        Account institution  # noqa: E501

        :return: The institution_id of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """Sets the institution_id of this ShortAccount.

        Account institution  # noqa: E501

        :param institution_id: The institution_id of this ShortAccount.  # noqa: E501
        :type: int
        """

        self._institution_id = institution_id

    @property
    def email(self):
        """Gets the email of this ShortAccount.  # noqa: E501

        User email  # noqa: E501

        :return: The email of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ShortAccount.

        User email  # noqa: E501

        :param email: The email of this ShortAccount.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def active(self):
        """Gets the active of this ShortAccount.  # noqa: E501

        Account activity status  # noqa: E501

        :return: The active of this ShortAccount.  # noqa: E501
        :rtype: int
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ShortAccount.

        Account activity status  # noqa: E501

        :param active: The active of this ShortAccount.  # noqa: E501
        :type: int
        """

        self._active = active

    @property
    def institution_user_id(self):
        """Gets the institution_user_id of this ShortAccount.  # noqa: E501

        Account institution user id  # noqa: E501

        :return: The institution_user_id of this ShortAccount.  # noqa: E501
        :rtype: str
        """
        return self._institution_user_id

    @institution_user_id.setter
    def institution_user_id(self, institution_user_id):
        """Sets the institution_user_id of this ShortAccount.

        Account institution user id  # noqa: E501

        :param institution_user_id: The institution_user_id of this ShortAccount.  # noqa: E501
        :type: str
        """

        self._institution_user_id = institution_user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShortAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShortAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
