# coding: utf-8

# flake8: noqa

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.articles_api import ArticlesApi
from swagger_client.api.authors_api import AuthorsApi
from swagger_client.api.collections_api import CollectionsApi
from swagger_client.api.institutions_api import InstitutionsApi
from swagger_client.api.other_api import OtherApi
from swagger_client.api.projects_api import ProjectsApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.account import Account
from swagger_client.models.account_create import AccountCreate
from swagger_client.models.account_group_roles import AccountGroupRoles
from swagger_client.models.account_group_roles_create import AccountGroupRolesCreate
from swagger_client.models.account_report import AccountReport
from swagger_client.models.account_update import AccountUpdate
from swagger_client.models.article import Article
from swagger_client.models.article_complete import ArticleComplete
from swagger_client.models.article_complete_private import ArticleCompletePrivate
from swagger_client.models.article_confidentiality import ArticleConfidentiality
from swagger_client.models.article_create import ArticleCreate
from swagger_client.models.article_doi import ArticleDOI
from swagger_client.models.article_embargo import ArticleEmbargo
from swagger_client.models.article_embargo_updater import ArticleEmbargoUpdater
from swagger_client.models.article_handle import ArticleHandle
from swagger_client.models.article_search import ArticleSearch
from swagger_client.models.article_update import ArticleUpdate
from swagger_client.models.article_versions import ArticleVersions
from swagger_client.models.articles_creator import ArticlesCreator
from swagger_client.models.author import Author
from swagger_client.models.author_complete import AuthorComplete
from swagger_client.models.authors_creator import AuthorsCreator
from swagger_client.models.categories_creator import CategoriesCreator
from swagger_client.models.category import Category
from swagger_client.models.collaborator import Collaborator
from swagger_client.models.collection import Collection
from swagger_client.models.collection_complete import CollectionComplete
from swagger_client.models.collection_create import CollectionCreate
from swagger_client.models.collection_doi import CollectionDOI
from swagger_client.models.collection_handle import CollectionHandle
from swagger_client.models.collection_private_link_creator import CollectionPrivateLinkCreator
from swagger_client.models.collection_search import CollectionSearch
from swagger_client.models.collection_update import CollectionUpdate
from swagger_client.models.collection_versions import CollectionVersions
from swagger_client.models.common_search import CommonSearch
from swagger_client.models.confidentiality_creator import ConfidentialityCreator
from swagger_client.models.curation import Curation
from swagger_client.models.curation_comment import CurationComment
from swagger_client.models.curation_comment_create import CurationCommentCreate
from swagger_client.models.curation_detail import CurationDetail
from swagger_client.models.custom_article_field import CustomArticleField
from swagger_client.models.error_message import ErrorMessage
from swagger_client.models.file_creator import FileCreator
from swagger_client.models.funding_create import FundingCreate
from swagger_client.models.funding_information import FundingInformation
from swagger_client.models.funding_search import FundingSearch
from swagger_client.models.group import Group
from swagger_client.models.institution import Institution
from swagger_client.models.institution_accounts_search import InstitutionAccountsSearch
from swagger_client.models.license import License
from swagger_client.models.location import Location
from swagger_client.models.private_article_search import PrivateArticleSearch
from swagger_client.models.private_authors_search import PrivateAuthorsSearch
from swagger_client.models.private_collection_search import PrivateCollectionSearch
from swagger_client.models.private_file import PrivateFile
from swagger_client.models.private_link import PrivateLink
from swagger_client.models.private_link_creator import PrivateLinkCreator
from swagger_client.models.project import Project
from swagger_client.models.project_article import ProjectArticle
from swagger_client.models.project_collaborator import ProjectCollaborator
from swagger_client.models.project_collaborator_invite import ProjectCollaboratorInvite
from swagger_client.models.project_complete import ProjectComplete
from swagger_client.models.project_complete_private import ProjectCompletePrivate
from swagger_client.models.project_create import ProjectCreate
from swagger_client.models.project_note import ProjectNote
from swagger_client.models.project_note_create import ProjectNoteCreate
from swagger_client.models.project_note_private import ProjectNotePrivate
from swagger_client.models.project_private import ProjectPrivate
from swagger_client.models.project_update import ProjectUpdate
from swagger_client.models.projects_search import ProjectsSearch
from swagger_client.models.public_file import PublicFile
from swagger_client.models.response_message import ResponseMessage
from swagger_client.models.role import Role
from swagger_client.models.short_account import ShortAccount
from swagger_client.models.timeline import Timeline
from swagger_client.models.timeline_update import TimelineUpdate
from swagger_client.models.upload_file_part import UploadFilePart
from swagger_client.models.upload_info import UploadInfo
from swagger_client.models.user import User
